collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1111111
color:
  saturation: 0.8902357
  brandStrength: 1
  lightness: 0.9005427
  brandColors:
    - '#202F4B'
    - '#87A4C5'
    - '#4A6489'
    - '#6786AC'
    - '#B3C7D7'
  rhythmicContrast: 0.8600081
layout_spectrum: 0.9749104
name: Altinkum
